Repository FACG5/Twig, pull requests merged in 2018-11, with the labels that each got.

#39 doc folder which contain pull request template
  doc/pull_request_template.md
Labels: Awaiting Review

#40 Initialize setup of project
  .eslintrc.json
  .travis.yml
  client/.gitignore
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  package.json
Labels: Approved

#45 Input common Component
  client/src/components/common/Inputs/index.jsx
  client/src/components/common/Inputs/style.css
Labels: In Review

#48 Es7 with linter
  client/.eslintrc.json
  client/package.json
Labels: Approved

#46 Header
  .gitignore
  client/package-lock.json
  client/src/components/common/Button/style.css
  client/src/components/common/Header/index.jsx
  client/src/components/common/Header/logo1.png
  client/src/components/common/Header/style.css
  client/src/components/common/Inputs/style.css
  package-lock.json
  package.json
Labels: Approved

#47 Login model
  client/package.json
  client/src/components/HomePage/Modal/LoginModel/index.jsx
  client/src/components/HomePage/Modal/LoginModel/style.css
  client/src/components/HomePage/Modal/index.jsx
  client/src/components/HomePage/Modal/style.css
  client/src/components/common/Button/style.css
  client/src/components/common/Inputs/style.css
Labels: In Review

#50 Fix travis bug
  .travis.yml
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/index.js
  package-lock.json
  package.json
Labels: Awaiting Review

#51 HomePage
  client/src/App.jsx
  client/src/components/HomePage/home.jpeg
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/style.css
  client/src/index.css
Labels: Approved

#52 Join model
  client/src/components/HomePage/Modal/LoginModel/index.jsx
  client/src/components/HomePage/Modal/index.jsx
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/JoinModal/style.css
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/HomePage/modal/LoginModal/style.css
  client/src/components/common/Button/index.jsx
  client/src/components/common/Button/style.css
  client/src/components/common/Header/index.jsx
  client/src/index.js
Labels: Awaiting Review

#55 About us
  client/package-lock.json
  client/src/components/HomePage/AboutUs/aboutUs.jpeg
  client/src/components/HomePage/AboutUs/index.jsx
  client/src/components/HomePage/AboutUs/style.css
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/style.css
  client/src/index.css
Labels: Approved

#61 Statistic
  client/src/components/HomePage/Statistic/index.jsx
  client/src/components/HomePage/Statistic/satistic.jpeg
  client/src/components/HomePage/Statistic/style.css
  client/src/components/HomePage/background.jpeg
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/style.css
Labels: Approved

#63 footer
  client/src/components/HomePage/index.jsx
  client/src/components/common/Footer/index.jsx
  client/src/components/common/Footer/style.css
Labels: Approved

#64 footer
  client/src/components/common/Footer/style.css
Labels: Approved

#65 create-mainpage-base-component
  client/src/components/MainPage/index.jsx
  client/src/components/MainPage/style.css
Labels: Approved

#67 React router
  client/package-lock.json
  client/package.json
  client/src/App.jsx
Labels: Approved

#58 Complete Join Details Model
  client/.eslintrc.json
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/style.css
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/style.css
  client/src/components/HomePage/modal/JoinModal/JoinDetails/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/style.css
  client/src/components/HomePage/modal/JoinModal/ValidationPopUp/index.jsx
  client/src/components/HomePage/modal/JoinModal/ValidationPopUp/style.css
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/JoinModal/style.css
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/HomePage/modal/LoginModal/style.css
  client/src/components/common/Button/style.css
  client/src/components/common/Inputs/index.jsx
  client/src/components/common/Inputs/style.css
  client/src/index.css
Labels: change requested

#68 Progress bar card
  client/src/components/MainPage/index.jsx
  client/src/components/MainPage/style.css
  client/src/components/common/Header/style.css
  client/src/components/common/ProgressBar/index.jsx
  client/src/components/common/ProgressBar/style.css
  client/src/index.css
Labels: Approved

#70 card component
  client/src/components/common/Cards/index.jsx
  client/src/components/common/Cards/style.css
  client/src/components/common/Footer/style.css
Labels: Approved

#75 Remove index issue
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/index.jsx
  client/src/components/common/Header/index.jsx
Labels: Approved

#69 Profile Card Component
  client/src/assets/img_avatar.png
  client/src/components/MainPage/index.jsx
  client/src/components/MainPage/style.css
  client/src/components/common/Button/style.css
  client/src/components/common/Footer/style.css
  client/src/components/common/ProfileCard/index.jsx
  client/src/components/common/ProfileCard/style.css
  client/src/components/common/ProgressBar/style.css
Labels: Approved

#77 SearchBar component
  client/src/components/HomePage/index.jsx
  client/src/components/MainPage/index.jsx
  client/src/components/common/SearchBar/index.jsx
  client/src/components/common/SearchBar/style.css
Labels: Approved

#90 Render Header and Footer in app component
  client/src/App.jsx
  client/src/components/HomePage/index.jsx
  client/src/components/MainPage/index.jsx
Labels: Awaiting Review

#93 Profile page - aboutMe
  client/src/components/ProfilePage/About/AboutMe/index.jsx
  client/src/components/ProfilePage/About/AboutMe/style.css
Labels: Approved

#78 Questions Page
  client/src/App.jsx
  client/src/components/QuestionsPage/QuestionCard/index.jsx
  client/src/components/QuestionsPage/QuestionCard/style.css
  client/src/components/QuestionsPage/Select/index.jsx
  client/src/components/QuestionsPage/Select/style.css
  client/src/components/QuestionsPage/image.png
  client/src/components/QuestionsPage/index.jsx
  client/src/components/QuestionsPage/style.css
  client/src/components/common/Cards/index.jsx
  client/src/components/common/Cards/style.css
  client/src/components/common/SearchBar/style.css
Labels: Approved

#97 Profile page - Translations
  client/src/components/ProfilePage/Translations/index.jsx
  client/src/components/ProfilePage/Translations/style.css
Labels: Approved

#92 Profile page - Profile Card Component
  client/src/components/ProfilePage/ProfileCard/index.jsx
  client/src/components/ProfilePage/ProfileCard/style.css
  client/src/components/ProfilePage/style.css
Labels: Approved

#94 Translation Page
  client/src/App.jsx
  client/src/components/TranslationsPage/TranslationCard/index.jsx
  client/src/components/TranslationsPage/TranslationCard/style.css
  client/src/components/TranslationsPage/index.jsx
  client/src/components/TranslationsPage/style.css
  client/src/components/common/Button/style.css
Labels: Approved

#96 Profile page - Overview
  client/src/components/ProfilePage/About/Overview/OverviewInformation/index.jsx
  client/src/components/ProfilePage/About/Overview/OverviewInformation/style.css
  client/src/components/ProfilePage/About/Overview/index.jsx
  client/src/components/ProfilePage/About/Overview/style.css
  client/src/index.js
Labels: Approved

#95 Profile page - language section
  client/src/components/ProfilePage/About/LanguageLevel/index.jsx
  client/src/components/ProfilePage/About/LanguageLevel/style.css
Labels: Approved

#99 Profile page - About
  client/src/components/ProfilePage/About/index.jsx
Labels: Approved

#102 Fixing landing page
  client/src/components/HomePage/Statistic/style.css
  client/src/components/HomePage/index.jsx
  client/src/components/HomePage/style.css
  client/src/components/common/Footer/style.css
Labels: Approved

#104 Donate translation modal
  client/src/components/HomePage/modal/JoinModal/style.css
  client/src/components/TranslationsPage/DonateModal/index.jsx
  client/src/components/TranslationsPage/DonateModal/style.css
  client/src/components/TranslationsPage/index.jsx
  client/src/components/common/Button/style.css
Labels: Approved

#109 Text translation modal
  client/src/components/TranslationsPage/DonateModal/TextTranslation/index.jsx
  client/src/components/TranslationsPage/DonateModal/TextTranslation/style.css
  client/src/components/TranslationsPage/DonateModal/index.jsx
  client/src/components/common/Button/style.css
Labels: Approved

#107 Specialization view
  client/src/assets/cardiac.png
  client/src/assets/general.png
  client/src/assets/orthopedics.png
  client/src/assets/psychiatry.png
  client/src/components/MainPage/SpecializationCard/index.jsx
  client/src/components/MainPage/SpecializationCard/style.css
  client/src/components/MainPage/index.jsx
  client/src/components/MainPage/style.css
  client/src/components/TranslationsPage/style.css
Labels: Approved

#111 Video translation modal
  client/src/components/TranslationsPage/DonateModal/VideoTranslation/index.jsx
  client/src/components/TranslationsPage/DonateModal/VideoTranslation/style.css
  client/src/components/TranslationsPage/DonateModal/index.jsx
Labels: Approved

#112 fix profile main style
  client/src/components/ProfilePage/style.css
Labels: Approved

#117 Fixing Heroku deploy
  client/package-lock.json
  package.json
Labels: Approved

#123 Merge component in Main Page component
  client/src/App.jsx
  client/src/components/MainPage/QuestionsPage/QuestionCard/index.jsx
  client/src/components/MainPage/QuestionsPage/QuestionCard/style.css
  client/src/components/MainPage/QuestionsPage/Select/index.jsx
  client/src/components/MainPage/QuestionsPage/Select/style.css
  client/src/components/MainPage/QuestionsPage/image.png
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/QuestionsPage/style.css
  client/src/components/MainPage/SpecializationCard/index.jsx
  client/src/components/MainPage/Spectialization/SpecializationCard/index.jsx
  client/src/components/MainPage/Spectialization/SpecializationCard/style.css
  client/src/components/MainPage/Spectialization/index.jsx
  client/src/components/MainPage/Spectialization/style.css
  client/src/components/MainPage/TranslationsPage/DonateModal/AudioTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/AudioTranslation/style.css
  client/src/components/MainPage/TranslationsPage/DonateModal/TextTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/TextTranslation/style.css
  client/src/components/MainPage/TranslationsPage/DonateModal/VideoTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/VideoTranslation/style.css
  client/src/components/MainPage/TranslationsPage/DonateModal/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/style.css
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  client/src/components/MainPage/TranslationsPage/TranslationCard/style.css
  client/src/components/MainPage/TranslationsPage/index.jsx
  client/src/components/MainPage/TranslationsPage/style.css
  client/src/components/MainPage/index.jsx
  client/src/components/MainPage/style.css
  client/src/components/QuestionsPage/style.css
  client/src/components/TranslationsPage/index.jsx
  client/src/components/TranslationsPage/style.css
Labels: Approved

#122 Change project title
  client/public/favicon.ico
  client/public/index.html
Labels: Approved

#118 Links pages
  client/.eslintrc.json
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/MainPage/QuestionsPage/QuestionCard/index.jsx
  client/src/components/MainPage/QuestionsPage/QuestionCard/style.css
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/Spectialization/SpecializationCard/index.jsx
  client/src/components/MainPage/Spectialization/SpecializationCard/style.css
  client/src/components/common/Header/index.jsx
Labels: Approved

#127 delete the Router tag from MainPage Component
  client/src/components/MainPage/index.jsx
Labels: Approved

#125 Remove links in profile page
  client/src/components/ProfilePage/index.jsx
  client/src/components/ProfilePage/style.css
  client/src/components/common/Button/style.css
Labels: Approved

#134 creating React Context for join process join
  client/.eslintrc.json
  client/src/App.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/index.jsx
  client/src/components/HomePage/modal/JoinModal/ValidationPopUp/index.jsx
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/ModalContext/index.jsx
  client/src/components/common/Header/index.jsx
  client/src/components/common/Inputs/index.jsx
  client/src/components/common/Inputs/style.css
Labels: Approved

#135 Create database schema
  config.js
  package.json
  server/database/config/index.js
  server/database/models/dialect.js
  server/database/models/index.js
  server/database/models/languages.js
  server/database/models/question.js
  server/database/models/speclalizations.js
  server/database/models/translations.js
  server/database/models/typesOTranslations.js
  server/database/models/users.js
  server/index.js
Labels: Approved

#136 Context join
  client/src/App.jsx
  package.json
Labels: Approved

#138 adding Language and dialect drop list to join Modal
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/Select/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/Select/style.css
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/style.css
  client/src/components/HomePage/modal/ModalContext/index.jsx
  server/app.js
Labels: Approved

#143 Travis new config
  .gitignore
  .travis.yml
  package-lock.json
  package.json
Labels: Approved

#145 Common component - popup
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/ValidationPopUp/index.jsx
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/ModalContext/index.jsx
  client/src/components/common/Header/index.jsx
  client/src/components/common/PopUp/index.jsx
  client/src/components/common/PopUp/style.css
  server/app.js
  server/database/config/index.js
Labels: Approved

#146 Login backend
  client/package.json
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/Select/index.jsx
  client/src/components/HomePage/modal/LoginModal/index.jsx
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/login.js
  server/database/models/index.js
  server/database/models/users.js
Labels: Approved

#149 add-package-lock.json-to-master-branch
  client/package-lock.json
  package-lock.json
Labels: Approved

#152 Back-end Question Page
  package-lock.json
  server/app.js
  server/controller/getQuestions.js
  server/controller/index.js
  server/database/fakeData.sql
  server/database/query/getQuestions.js
Labels: Approved

#153 Protect Route if not login
  client/package.json
  client/src/App.jsx
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/PrivateRoutes/index.jsx
  package-lock.json
  package.json
  server/app.js
  server/controller/authentication/index.js
Labels: Approved

#159 Fix login bug
  client/package-lock.json
  client/src/components/HomePage/modal/LoginModal/index.jsx
  package-lock.json
Labels: Approved

#165 Search and filter function
  client/src/components/MainPage/QuestionsPage/Select/index.jsx
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/QuestionsPage/style.css
  client/src/components/common/SearchBar/index.jsx
  package-lock.json
Labels: Approved

#168 Modify fake data
  server/database/fakeData.sql
Labels: Approved

#182 create Skills and jobs tables
  server/database/fakeData.sql
  server/database/models/employeeSkills.js
  server/database/models/index.js
  server/database/models/jobs.js
  server/database/models/skills.js
  server/database/models/users.js
Labels: Approved

#179 Back-end Translation Page
  server/controller/index.js
  server/controller/translations.js
  server/database/fakeData.sql
  server/database/query/translations.js
Labels: Approved

#183 Specialization search
  client/src/components/MainPage/QuestionsPage/style.css
  client/src/components/MainPage/Spectialization/index.jsx
  client/src/components/MainPage/Spectialization/style.css
Labels: Approved

#173 Signup frontend function
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/CheckBoxes/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/Jobs/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/style.css
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/HomePage/modal/ModalContext/index.jsx
  client/src/components/common/Inputs/index.jsx
Labels: Approved

#185 Front translations page
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
  client/src/components/MainPage/index.jsx
Labels: Approved

#193 Vote
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  server/database/fakeData.sql
  server/database/models/index.js
  server/database/models/translations.js
  server/database/models/vote.js
  server/database/query/translations.js
Labels: Approved

#188 Signup Backend
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/Select/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/Jobs/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/index.jsx
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/ModalContext/index.jsx
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/jobs.js
  server/controller/signup.js
  server/controller/skills.js
  server/database/fakeData.sql
Labels: Approved

#192 Language and dialect api
  server/controller/dialects.js
  server/controller/index.js
  server/controller/languages.js
Labels: Approved

#191 Language and dialects - Frontend
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/Select/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/ModalContext/index.jsx
Labels: Approved

#187 Profile card front-end
  client/src/components/MainPage/index.jsx
  client/src/components/common/ProfileCard/index.jsx
Labels: Approved

#186 Profile card backend
  package-lock.json
  server/controller/index.js
  server/controller/user.js
  server/database/query/userDetails.js
Labels: Approved

#199 add-default-value-to-users-avatar-img
  server/database/models/users.js
Labels: Approved

#213 creating error page
  client/src/components/ErrorPage/index.jsx
  client/src/components/ErrorPage/style.css
Labels: Approved

#209 Loading component
  client/src/components/common/Loading/index.jsx
  client/src/components/common/Loading/style.css
Labels: Approved

#220 Header buttons and link on logo
  client/src/components/common/Header/LoggedinButtons/index.jsx
  client/src/components/common/Header/NotLoginButtons/index.jsx
  client/src/components/common/Header/index.jsx
Labels: Approved

#217 Handling the errors
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/Spectialization/index.jsx
  client/src/components/MainPage/Spectialization/style.css
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
  client/src/components/common/Button/style.css
  server/controller/questions.js
  server/controller/speclalization.js
  server/controller/translations.js
Labels: Approved

#202 Vote up back end
  server/controller/index.js
  server/controller/voteUp.js
  server/database/fakeData.sql
  server/database/query/questions.js
Labels: Approved

#221 Profile page frontend
  client/src/components/ProfilePage/About/AboutMe/index.jsx
  client/src/components/ProfilePage/About/Overview/OverviewInformation/index.jsx
  client/src/components/ProfilePage/About/Overview/index.jsx
  client/src/components/ProfilePage/ProfileCard/index.jsx
  client/src/index.js
Labels: Approved

#211 Profile page backend
  server/controller/index.js
  server/controller/signup.js
  server/controller/user.js
  server/database/fakeData.sql
  server/database/models/users.js
  server/database/query/userDetails.js
  server/database/query/users.js
Labels: Approved

#206 Front vote down
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
Labels: Approved

#224 Render loading component in Specialization, Questions, Translations
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/Spectialization/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
  client/src/components/common/Loading/style.css
  client/src/components/layouts/MainLayout/index.jsx
Labels: Approved

#225 adding the route of ErrorPage in App Component
  client/src/App.jsx
Labels: Approved

#226 Profile backend
  server/controller/user.js
  server/database/query/users.js
Labels: Approved

#231 Check vote
  client/src/components/MainPage/TranslationsPage/TranslationCard/index.jsx
  server/controller/voteDown.js
  server/controller/voteUp.js
Labels: Approved

#233 Fix bug search
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/Spectialization/index.jsx
Labels: Approved

#232 Language level section frontend
  client/src/components/ProfilePage/About/AboutMe/index.jsx
  client/src/components/ProfilePage/About/LanguageLevel/index.jsx
  client/src/components/ProfilePage/About/LanguageLevel/style.css
  client/src/components/ProfilePage/About/Overview/index.jsx
  client/src/components/ProfilePage/ProfileCard/index.jsx
  server/database/query/users.js
Labels: Awaiting Review

#234 Loading in Modal login and join
  client/src/App.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageOne/index.jsx
  client/src/components/HomePage/modal/JoinModal/JoinDetails/StageTwo/index.jsx
  client/src/components/HomePage/modal/JoinModal/index.jsx
  client/src/components/HomePage/modal/JoinModal/style.css
  client/src/components/HomePage/modal/LoadingModal/index.jsx
  client/src/components/HomePage/modal/LoadingModal/style.css
  client/src/components/HomePage/modal/LoginModal/index.jsx
  client/src/components/HomePage/modal/LoginModal/style.css
  client/src/components/HomePage/modal/ModalContext/index.jsx
  client/src/components/common/PopUp/index.jsx
Labels: Approved

#236 Profile layout
  client/src/App.jsx
  client/src/components/ProfilePage/About/LanguageLevel/index.jsx
  client/src/components/ProfilePage/index.jsx
  client/src/components/layouts/ProfileLayout/index.jsx
Labels: Approved

#241 Add question modal
  client/src/components/MainPage/QuestionsPage/AddQuestionModal/index.jsx
  client/src/components/MainPage/QuestionsPage/AddQuestionModal/style.css
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/common/Button/style.css
Labels: Approved

#240 Profile component refactoring
  client/src/App.jsx
  client/src/components/HomePage/modal/LoadingModal/index.jsx
  client/src/components/HomePage/modal/LoadingModal/style.css
  client/src/components/ProfilePage/About/AboutMe/index.jsx
  client/src/components/ProfilePage/About/LanguageLevel/index.jsx
  client/src/components/ProfilePage/About/Overview/index.jsx
  client/src/components/ProfilePage/About/index.jsx
  client/src/components/ProfilePage/ProfileCard/index.jsx
  client/src/components/ProfilePage/index.jsx
  client/src/components/common/Header/index.jsx
  client/src/components/common/Loading/style.css
  client/src/components/layouts/DefaultLayout/index.jsx
  client/src/components/layouts/ProfileLayout/index.jsx
Labels: Approved

#243 Header Dashboard button
  client/src/components/common/Button/index.jsx
  client/src/components/common/Button/style.css
  client/src/components/common/Header/NotLoginButtons/index.jsx
Labels: Approved

#244 handling the error in profile page
  client/src/components/ProfilePage/index.jsx
  client/src/components/common/Loading/style.css
Labels: Approved

#253 Upload audio front-end
  client/.eslintrc.json
  client/src/components/MainPage/TranslationsPage/DonateModal/AudioTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/index.jsx
Labels: Approved

#254 Upload file backend
  package-lock.json
  package.json
  server/app.js
  server/controller/index.js
  server/controller/translations.js
  server/controller/upload.js
  uploads/index.js
Labels: Approved

#255 remove flatmap-stream from package-lock
  package-lock.json
Labels: Approved

#250 Add question backend
  server/controller/index.js
  server/controller/questions.js
  server/database/fakeData.sql
  server/database/models/question.js
Labels: Approved

#249 Add question refactor frontend
  client/src/components/MainPage/QuestionsPage/AddQuestionModal/index.jsx
  client/src/components/MainPage/QuestionsPage/AddQuestionModal/style.css
  client/src/components/MainPage/QuestionsPage/QuestionCard/index.jsx
  client/src/components/MainPage/QuestionsPage/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
Labels: In progress

#258 Upload video front-end
  client/src/components/MainPage/TranslationsPage/DonateModal/AudioTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/TextTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/VideoTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/index.jsx
Labels: Approved

#261 Fixing bugs - rendering the Translations component in profile page
  client/src/components/ProfilePage/Translations/index.jsx
  client/src/components/ProfilePage/index.jsx
Labels: Approved

#267 Uploading files progress
  client/src/components/MainPage/TranslationsPage/DonateModal/AudioTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/VideoTranslation/index.jsx
  client/src/components/MainPage/TranslationsPage/DonateModal/index.jsx
Labels: Approved

#269 Fix bug question page
  client/src/components/MainPage/QuestionsPage/QuestionCard/index.jsx
  client/src/components/MainPage/TranslationsPage/index.jsx
Labels: Approved

#274 Bradly data
  client/src/components/MainPage/QuestionsPage/index.jsx
  server/database/dataBradley.sql
Labels: Awaiting Review
